name: "Publish package to GitHub Packages"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: "Setup Node.js"
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: "24.x"
          registry-url: 'https://npm.pkg.github.com'

      - name: "Install dependencies"
        run: npm ci --no-fund

      - name: "Build package"
        run: npm run build:prod

      - name: "Publish to GitHub Packages"
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
